import type { Metadata } from "next";
import "./globals.css";
import Sidebar from './components/Sidebar'
import Header from './components/Header'

export const metadata: Metadata = {
  title: "Switch-Control",
  description: "Generated by Switch-Control",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex items-start min-h-screen">
        <Sidebar />
        <div className="w-full flex flex-col gap-5 flex-1">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
